parameters:
- name: experimentalTemplate
  displayName: 'Use experimental build process?'
  type: boolean
  default: false

steps:
- ${{ if eq(parameters.experimentalTemplate, true) }}:
  - template: simple-param.yaml
- ${{ if not(eq(parameters.experimentalTemplate, true)) }}:
  - template: simple-param.yaml
