variables:
  mySimpleVar: simple var value
jobs:
- job: myJob
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo a >> a.txt
  - script: cat a.txt
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: taba
      artifactName: WebSite




