trigger: 
- main

pool: 
   vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: test
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: touch /tmp/mytest



